@ NOTE: The brailleformat macro in this file is leftover from RS.
@       The numbers are simply skipped over. If you'd like to omit
@       this macro you must also stop it from skipping over this
@       section by editing ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "ZAI CI\n"
	.braille "SHANG SHENG$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "ZAI CI\n"
	.braille "WA DONG$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "HOU JING WANG\n"
	.braille "WEI SHI\n"
	.braille "GU KONG JI YU\n"
	.braille "WEI MO\n"
	.braille "XI SHU JIN KAI$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "WU DENG\n"
	.braille "JU CI KU ZHONG\n"
	.braille "CUN YU CI CHU$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "CI JIE\n"
	.braille "LAI YU\n"
	.braille "BAO KE MENG$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "RAN WU DENG\n"
	.braille "JIANG QI\n"
	.braille "FENG YIN$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "JIE YIN QI$\n"
	.braille "SHI ZAI$\n"
	.braille "GUO YU KE BU$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "YONG GAN\n"
	.braille "ZHI REN\n"
	.braille "XIONG CUN\n"
	.braille "XI JI\n"
	.braille "ZHI REN$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "KAI CI MEN\n"
	.braille "YONG HENG ZHI\n"
	.braille "BAO KE MENG\n"
	.braille "WEI HU\n"
	.braille "QI ZHONG$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "ZUO ZUO\n"
	.braille "XIA XIA\n"
	.braille "ZAI CI\n"
	.braille "SUI YAN$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "HUAN CI\n"
	.braille "QIANG BI\n"
	.braille "ZHOU ER\n"
	.braille "XING ZHI$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "CHENG WU DENG\n"
	.braille "ZHI ZHI ZHE\n"
	.braille "YAO RU ZHI\n"
	.braille "GUANG YU CI\n"
	.braille "ZHENG ZHONG$"
