gText_AppealNumWhichMoveWillBePlayed::
	.string "第{STR_VAR_1}回合的表演！\n"
	.string "要使用哪个招式呢？$" 
@{STR_VAR_1}かいめのアピール！
@どのわざをつかう？

gText_AppealNumButItCantParticipate::
	.string "第{STR_VAR_1}回合的表演！\n"
	.string "但是不能参加！$"
@{STR_VAR_1}かいめのアピール！
@しかしさんかできない！

gText_MonAppealedWithMove::
	.string "{STR_VAR_1}使用了\n"
	.string "{STR_VAR_2}来表演！$"
@{STR_VAR_1}は
@{STR_VAR_2}でアピール！

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1}\n"
	.string "看了看大家！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は
@みんなを　みていた！

gText_AllOutOfAppealTime::
	.string "表演时间结束！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@アピールタイム しゅうりょう！

@ Appeal result texts
gText_BecameMoreConsciousOfOtherMons::
    .string "其它宝可梦相比平常，\n"
    .string "变得更担心了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ほかの　ポケモンが　いつもより
@きに　なって　きた！

gText_MonCantMakeAnAppealAfterThis::
    .string "{STR_VAR_1}在这之后\n"
    .string "就不能登台表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　このあと
@アピール　できなく　なった！

gText_SettledDownJustLittleBit::
    .string "它稍稍有点\n"
    .string "心情平静了下来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ちょっと　だけ
@きもちが　おちついた！

gText_BecameObliviousToOtherMons::
    .string "它变得完全\n"
    .string "不关注其它宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ほかの　ポケモンが　ぜんぜん
@きに　ならなく　なった！

gText_BecameLessAwareOfOtherMons::
    .string "它变得不怎么去\n"
    .string "关注其它宝可梦了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ほかの　ポケモンが　あまり
@きに　ならなく　なった！

gText_StoppedCaringAboutOtherMons::
    .string "它变得不怎么去\n"
    .string "分心或留意其它宝可梦了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ほかの　ポケモンを　あまり
@きに　しないように　なった！

gText_TriedToStartleOtherMons::
	.string "它想要把其他的\n"
	.string "宝可梦吓一跳！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ほかの　ポケモンを
@びっくり　させようと　した！

gText_TriedToDazzleOthers::
    .string "它想要让大家\n"
    .string "都变得眼花起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@みんなの　めを
@くらませようと　した！

gText_JudgeLookedAwayFromMon::
    .string "审查员的目光\n"
    .string "从{STR_VAR_1}身上移开了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@しんさいんは　{STR_VAR_1}から
@めを　そらして　しまった！

gText_TriedToUnnerveNextMon::
    .string "它想让下一只等待表演的\n"
    .string "宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@つぎに　まっている　ポケモンを
@きんちょう　させようと　した！

gText_MonBecameNervous::
    .string "{STR_VAR_1}\n"
    .string "紧张了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は
@きんちょう　してしまった！

gText_AppealTriedToUnnerveWaitingMons::
    .string "它想让所有没有表演的\n"
    .string "宝可梦紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@アピールが　まだの　ポケモンを
@きんちょう　させようと　した！

gText_TauntedMonsDoingWell::
    .string "它试着去嘲笑捉弄那些\n"
    .string "气势还不错的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ちょうしが　いい　ポケモンを
@からかってみた！

gText_MonRegainedItsForm::
    .string "{STR_VAR_1}的气势\n"
    .string "回到了本来的样子！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　ちょうしが
@もとに　もどって　しまった！

gText_TriedToJamMonDoingWell::
    .string "它想去打扰那些\n"
    .string "气势还不错的宝可梦！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ちょうしが　いい　ポケモンの
@じゃまを　しようと　した！

gText_StandoutMonHustledEvenMore::
	.string "本来就十分显眼的{STR_VAR_1}\n"
	.string "更是鼓足了干劲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@めだっている　{STR_VAR_1}は
@さらに　はりきった！

gText_LargelyUnnoticedMonWorkedHard::
    .string "本来不太显眼的{STR_VAR_1}\n"
    .string "加油努力了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@めだっていない　{STR_VAR_1}は
@がんばりまくった！

gText_WorkedAsMuchAsMonBefore::
    .string "它鼓足了不会输给\n"
    .string "前面宝可梦们程度的干劲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@まえの　ポケモンたちに
@まけないくらい　はりきった！

gText_MonsAppealDidNotGoWell::
    .string "{STR_VAR_1}并没有\n"
    .string "展示表演出自己的水平！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　アピールを
@うまく　みせられなかった！

gText_WorkedAsMuchAsPrecedingMon::
    .string "和前面的宝可梦\n"
    .string "一样地鼓足了干劲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@まえの　ポケモンと
@おなじくらい　はりきった！

gText_MonsAppealDidNotGoWell2::
    .string "{STR_VAR_1}并没有\n"
    .string "展示表演出自己的水平！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　アピールを
@うまく　みせられなかった！

gText_MonsAppealDidNotGoWell3::
    .string "{STR_VAR_1}并没有\n"
    .string "展示表演出自己的水平！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　アピールを
@うまく　みせられなかった！

gText_MonsAppealWentSlightlyWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得有点可以！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@すこし　うまく　いった！

gText_MonsAppealWentPrettyWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得还算不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@まあまあ　うまく　いった！

gText_MonsAppealWentExcellently::
    .string "{STR_VAR_1}的表演\n"
    .string "做得非常不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@とても　うまく　いった！

gText_MonsAppealWasDud::
    .string "{STR_VAR_1}的表演\n"
    .string "成了一场失败！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@しっぱい　して　しまった！

gText_MonsAppealDidNotWorkVeryWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得不怎么好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@あまり　うまく　いかなかった！

gText_MonsAppealWentSlightlyWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得有点可以！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@すこし　うまく　いった！

gText_MonsAppealWentPrettyWell2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得还算不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@まあまあ　うまく　いった！

gText_MonsAppealWentVeryWell::
    .string "{STR_VAR_1}的表演\n"
    .string "做得相当可以！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@かなり　うまく　いった！

gText_MonsAppealWentExcellently2::
    .string "{STR_VAR_1}的表演\n"
    .string "做得非常不错！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　アピールは
@とても　うまく　いった！

gText_SameTypeAsOneBeforeGood::
    .string "因为和前面的宝可梦\n"
    .string "一样类型而受到喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@まえの　ポケモンと
@おなじタイプで　きにいられた！

gText_NotSameTypeAsOneBeforeGood::
    .string "因为和前面的宝可梦\n"
    .string "类型不同而受到喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@まえの　ポケモンと
@ちがうタイプで　きにいられた！

gText_StoodOutMuchMoreThanMonBefore::
    .string "相比前面的宝可梦\n"
    .string "要出彩得多！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@まえの　ポケモンより
@だいぶ　めだった！

gText_DidntDoAsWellAsMonBefore::
    .string "相比前面的宝可梦\n"
    .string "完成得不算太好！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@まえの　ポケモンより
@うまく　できなかった！

gText_MonsConditionRoseAboveUsual::
    .string "{STR_VAR_1}的气势\n"
    .string "相比平常有所提升！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　ちょうしが
@いつもより　あがった！

gText_MonsHotStatusMadeGreatAppeal::
    .string "{STR_VAR_1}气势不错\n"
    .string "表演变得棒极了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　ちょうしが　よくて
@ぜっこうの　アピールに　なった！

gText_MovedUpInLineForNextAppeal::
	.string "它想要在下回合的表演里\n"
	.string "更早出场而走到了前面！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@つぎの　アピールを　はやく
@しようと　まえに　でた！

gText_MovedBackInLineForNextAppeal::
	.string "它想要在下回合的表演里\n"
	.string "更晚出场而后退了一步！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@つぎの　アピールを　おそく
@しようと　１ぽ　さがった！

gText_ScrambledUpOrderForNextTurn::
	.string "下个回合的表演顺序\n"
	.string "变得奇怪了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@つぎの　ターンの　じゅんばん
@おかしく　した！

gText_JudgeLookedAtMonExpectantly::
	.string "审查员满怀期待地\n"
	.string "看着{STR_VAR_1}！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@しんさいんが　きたいして
@{STR_VAR_1}を みつめた！

gText_AppealComboWentOverWell::
    .string "前后两场表演的组合\n"
	.string "得到了大家的喜爱！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@アピールの　くみあわせが
@きに　いって　もらえた！

gText_AppealComboWentOverVeryWell::
    .string "前后两场表演的组合\n"
	.string "相当受大家喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@アピールの　くみあわせが
@かなり　きに　いられた！

gText_AppealComboWentOverExcellently::
    .string "前后两场表演的组合\n"
	.string "特别受大家喜欢！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@アピールの　くみあわせが
@ものすごく　きに　いられた！

gText_MonManagedToAvertGaze::
    .string "{STR_VAR_1}不知为何\n"
    .string "没有看它！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　なんとか
@めを　そらした！

gText_MonManagedToAvoidSeeingIt::
    .string "{STR_VAR_1}\n"
    .string "没看向那里而没有被吓到！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は
@そっちを　みずに　すんだ！

gText_MonIsntFazedByThatSortOfThing::
    .string "这种程度的事情\n"
    .string "没有对{STR_VAR_1}造成影响！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は
@このくらいは　へいきだった！

gText_MonBecameALittleDistracted::
    .string "{STR_VAR_1}变得\n"
    .string "稍稍有点分心了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　ちょっと
@きを　とられて　しまった！

gText_TriedToStartleOtherPokemon::
	.string "它想要把其他的\n"
	.string "宝可梦吓一跳！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ほかの　ポケモンを
@びっくり　させようと　した！

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1}被吸引了注意力\n"
	.string "低头看向下面了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　きをとられて
@したを　むいて　しまった！（小）

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1}被吸引了注意力\n"
	.string "转过头去了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　きを　とられて
@ふりかえって　しまった！（中）

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1}不受控制地\n"
	.string "提高了自己的声音！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　おもわず
@こえを　あげて　しまった！（大）

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1}不受控制地\n"
	.string "猛地跳了起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　おもわず
@とびあがって　しまった！（特大）

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1}被吸引了注意力\n"
	.string "摔在了地上四脚朝天！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　きを　とられて
@ひっくり　かえって　しまった！（？）

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1}因为紧张\n"
	.string "不能使用招式表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　きんちょうして
@アピールが　できなかった！

gText_ButItMessedUp2::
	.string "但是最终失败了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@でも　しっぱい　してしまった！

gText_ButItFailedToMakeTargetNervous::
	.string "但是没有成功\n"
	.string "使宝可梦紧张起来！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@でも　きんちょう
@させられなかった！

gText_ButItFailedToMakeAnyoneNervous::
	.string "但是场上的宝可梦们\n"
	.string "谁都没有紧张！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@でも　だれも
@きんちょう　しなかった！

gText_ButItWasIgnored::
    .string "但是被无视了……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@でも　むし　されて　しまった……

gText_CouldntImproveItsCondition::
	.string "但是气势\n"
    .string "并没有被提升……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@でも　ちょうしは
@あがらなかった……

gText_BadConditionResultedInWeakAppeal::
	.string "它因为气势不行\n"
    .string "表演得一点也不好……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@ちょうしが　よく　なくて
@あまり　うまく　できなかった……

gText_MonWasUnaffected::
	.string "{STR_VAR_1}\n"
    .string "依然气定神闲！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は
@へいき　だった！

gText_RepeatedAppeal::
    .string "{STR_VAR_1}持续表演\n"
    .string "相同的招式真让人失望。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　おなじアピールを
@つづけて　がっかり　された！

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "受到了周围的热烈欢迎！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　{STR_VAR_3}が
@まわりに　とても　うけた！

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "在这里不被接受……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　{STR_VAR_3}が
@ここでは　うけなかった…

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}的{STR_VAR_3}表演\n"
	.string "让整个会场沸腾了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　{STR_VAR_3}に
@まわりが　もりあがった！

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1}不能参加\n"
    .string "之后的表演了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}は　つぎの　アピールに
@さんか　できなくなった！

gText_AttractedCrowdsAttention::
	.string "吸引了\n"
    .string "观众们的注意！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@かんきゃくの
@ちゅうもくを　あつめた！

gText_CrowdContinuesToWatchMon::
	.string "观众们一直\n"
    .string "持续看着{STR_VAR_3}！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@かんきゃくは
@{STR_VAR_3}を　みつづけている！

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}的{STR_VAR_2}\n"
    .string "连看都没人看……{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
@{STR_VAR_1}の　{STR_VAR_2}は
@めを　むけられなかった……

gText_Contest_Shyness::
    .string "扑通扑通$"
@ドキドキ

gText_Contest_Anxiety::
    .string "慌慌张张$"
@モジモジ

gText_Contest_Laziness::
    .string "懒懒洋洋$"
@テレテレ

gText_Contest_Hesitancy::
    .string "犹犹豫豫$"
@オロオロ

@ビクビク
gText_Contest_Fear::
	.string "战战栗栗$"
