gText_AppealNumWhichMoveWillBePlayed::
    .string "{STR_VAR_1}号表演！\n要选择什么招式呢？$"

gText_AppealNumButItCantParticipate::
    .string "{STR_VAR_1}号表演！\n但是它无法参与！$"

gText_MonAppealedWithMove::
    .string "{STR_VAR_1}使用\n{STR_VAR_2}进行表演！$"

gText_MonWasWatchingOthers::
    .string "{STR_VAR_1}正在\n看着别人。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
    .string "表演时间\n已经结束了！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
    .string "其它宝可梦变得\n更警惕了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
    .string "{STR_VAR_1}在这之后\n不能再使用招式了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
    .string "它稍微\n冷静下来了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
    .string "它开始忽视\n其它宝可梦了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
    .string "其它宝可梦的\n关注度降低了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
    .string "它无视了\n其它宝可梦。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
    .string "它试着去惊吓\n其它宝可梦。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
    .string "它尝试让其它\n宝可梦眼花。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
    .string "裁判不再看\n {STR_VAR_1}了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
    .string "它想让下一位\n宝可梦泄气。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
    .string "{STR_VAR_1}变得\n紧张了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
    .string "它让在等待的\n宝可梦胆怯了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
    .string "它让其它宝可梦\n受到了惊吓。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
    .string "{STR_VAR_1}恢复了。\n{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
    .string "它试图干扰宝可梦\n把招式做好。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
    .string "表现出色的{STR_VAR_1}\n加快步伐甩开对手。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
    .string "不太受人注意的\n{STR_VAR_1}做得更加的努力。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
    .string "它和之前的那些宝可梦\n一样的的努力。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
    .string "{STR_VAR_1}的招式完成\n的不是很理想。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
    .string "和前面宝可梦的招式\n重复了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
    .string "{STR_VAR_1}的招式完成\n的不是很理想。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
    .string "{STR_VAR_1}的招式完成\n的不是很理想。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
    .string "{STR_VAR_1}的招式\n完成的还可以。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
    .string "{STR_VAR_1}的招式\n完成的非常好。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
    .string "{STR_VAR_1}的招式\n完成的太棒了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
    .string "{STR_VAR_1}的招式\n没有作用。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
    .string "{STR_VAR_1}的招式\n不是很有用。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
    .string "{STR_VAR_1}的招式\n完成的还可以。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
    .string "{STR_VAR_1}的招式\n完成的非常好。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
    .string "{STR_VAR_1}的招式\n完成的非常棒。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
    .string "{STR_VAR_1}的招式\n完成的太出色了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
    .string "和前面宝可梦的招式\n完成的一样出色！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
    .string "它和之前做相同\n招式的一样棒！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
    .string "它比前面的宝可梦\n要出色多了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
    .string "它还没有之前的\n宝可梦表演的精彩。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
    .string "{STR_VAR_1}的状态\n渐入佳境。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
    .string "{STR_VAR_1}的火热状态\n使得表演更加出色！{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
    .string "为了接下来的表演，\n它走到了前方。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
    .string "它向后退了步\n等待下一轮表演。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
    .string "下一轮的\n次序被打乱了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
    .string "裁判非常专注地\n看着{STR_VAR_1}的表演。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
    .string "连锁招式\n受到欢迎了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
    .string "连锁招式\n很受欢迎。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
    .string "连锁招式\n非常受欢迎了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
    .string "{STR_VAR_1}设法\n躲开了它的注视。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
    .string "{STR_VAR_1}设法\n避免看到它。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
    .string "{STR_VAR_1}并没有因为\n那些小插曲受影响。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
    .string "{STR_VAR_1}变得有些\n分心了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
    .string "它尝试惊吓\n其它宝可梦。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
    .string "{STR_VAR_1}低着头\n不知道在想什么。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
    .string "{STR_VAR_1}转过身子\n不知道在想什么。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
    .string "{STR_VAR_1}忍不住\n哭了出来。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
    .string "{STR_VAR_1}不禁地\n跳了起来。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
    .string "{STR_VAR_1}因为漫不经心\n而被绊倒了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
    .string "{STR_VAR_1}紧张得\n不得动弹了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
    .string "但是它陷入了困境。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
    .string "它想让对手紧张\n但失败了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
    .string "没有让任何\n一个宝可梦紧张。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
    .string "它被无视了…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
    .string "它还不能改善\n自己的状态…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
    .string "它糟糕的状态\n使得招式都是有气无力的了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
    .string "{STR_VAR_1}没有\n受到影响。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
    .string "{STR_VAR_1}用了重复的招式，\n真让人失望。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
    .string "{STR_VAR_1}的{STR_VAR_3}表演\n做得相当出色。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
    .string "{STR_VAR_1}的{STR_VAR_3}表演\n没有受到青睐…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
    .string "{STR_VAR_1}的{STR_VAR_3}表演\n让围观人群散去了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
    .string "{STR_VAR_1}下一轮\n不能行动了…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
    .string "它吸引了\n观众的注意。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
    .string "人们还在关注\n着{STR_VAR_3}。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
    .string "{STR_VAR_1}的\n{STR_VAR_2}被忽视了。{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
    .string "害羞$"

gText_Contest_Anxiety::
    .string "焦虑$"

gText_Contest_Laziness::
    .string "懒惰$"

gText_Contest_Hesitancy::
    .string "踌躇$"

gText_Contest_Fear::
	.string "恐惧$"
