EventTicket_Text_OldSeaMapTooFar::
	.string "你说什么，年轻人？\p什么，就是你拥有\n破烂的古老地图？\p让我看看。\n…… …… ……\p好家伙……这简直是遥不可及。\n我恐怕帮不了你……$"

EventTicket_Text_BrineyHoldOnASecond::
	.string "哈奇：喂！\p竟敢拒绝我恩人的请求\n这叫怎么一回事儿啊！$"

EventTicket_Text_BrineyLetsSail::
	.string "{PLAYER}{KUN}，真不好意思。\p你特意来这找我帮忙，\n可是我们差点把你拒之门外。\p让我来弥补\n这个错误吧。\p我们这就启航！\p让我们去找古航海图\n上的小岛吧！$"

EventTicket_Text_OddTicketGetOnBoard::
	.string "你带着船票了吗？\p你设法要去的岛\n在很远很远的地方。\p没人知道那里会有什么等着我们……\p这激起了我作为\n水手的热情！\p快上船来，年轻人！$"

FarawayIsland_Entrance_Text_SailorReturn::
	.string "哈奇船长善变的性格\n真让人抓狂……\p你想回到水静市吗？$"

BirthIsland_Harbor_Text_SailorReturn::
	.string "多么奇怪的小岛，不是吗？\n你想返回水静市吗？$"

EventTicket_Text_OddTicketsWhereTo::
	.string "你带着船票了吗？\p…… ……唔。\p这些船票能让你到一些小岛上去\n那是个很远很远的地方。\p没人知道那里会有什么等着我们，\n抑或是可能会发生什么。\p这激起了我作为\n水手的热情！\p快上船来，年轻人！\n我们先去哪？$"

NavelRock_Harbor_Text_SailorReturn::
	.string "你听……听到了吗？\n从深处传出的低吼。\p你确定这里安全吗？\n我们要不要离开这儿？$"

FarawayIsland_Entrance_Text_Sign::
	.string "字迹已经模糊不清\n仿佛已经写了很久很久了……\p“……月6日\n在踏进这里的……类面前\l再次……身的话\l希望他心地……良\l在……里写下这样的愿望后\l我离开了这个……\l\l……士”$"

FarawayIsland_Interior_Text_Mew::
	.string "咪呦……$"
