gText_ObtainedTheItem::
    .string "{PLAYER}获得了{STR_VAR_2}！$"

gText_TheBagIsFull::
    .string "包包满了………$"

gText_PutItemInPocket::
    .string "{PLAYER}把{STR_VAR_2}\n放入了{STR_VAR_3}口袋里。$"

gText_PlayerFoundOneItem::
    .string "{PLAYER}找到了{STR_VAR_2}！$"

gText_TooBadBagIsFull::
    .string "太遗憾了！\n包包满了……$"

gText_PlayerPutItemInBag::
    .string "{PLAYER}把{STR_VAR_2}\n放入了包包里。$"

gText_ObtainedTheDecor::
    .string "获得了{STR_VAR_2}！$"

gText_NoRoomLeftForAnother::
    .string "太遗憾了！{STR_VAR_2}的数量已满，\n没法再携带了！$"

gText_TheDecorWasTransferredToThePC::
    .string "{STR_VAR_2}传送到\n电脑里了。$"

gText_ObtainedTheItems::
	.string "{PLAYER}获得了\n{STR_VAR_1}个{STR_VAR_2}！$"

gText_PlayerFoundItems::
	.string "{PLAYER}找到了\n{STR_VAR_1}个{STR_VAR_2}！$"
