gText_ObtainedTheItem::
    .string "{PLAYER}得到了{STR_VAR_2}！$"

gText_TheBagIsFull::
    .string "背包满了………$"

gText_PutItemInPocket::
    .string "{PLAYER}把{STR_VAR_2}放进了\n背包的{STR_VAR_3}口袋。$"

gText_PlayerFoundOneItem::
    .string "{PLAYER}发现了{STR_VAR_2}！$"

gText_TooBadBagIsFull::
    .string "真可惜！\n背包满了…$"

gText_PlayerPutItemInBag::
    .string "{PLAYER}把{STR_VAR_2}\n放进了背包。$"

gText_ObtainedTheDecor::
    .string "得到了{STR_VAR_2}！$"

gText_NoRoomLeftForAnother::
    .string "可惜！没有再放下一个\n{STR_VAR_2}的空间了…$"

gText_TheDecorWasTransferredToThePC::
    .string "{STR_VAR_2}传进了\n电脑里。$"

gText_ObtainedTheItems::
	.string "{PLAYER}获得了\n{STR_VAR_1}个{STR_VAR_2}！$"

gText_PlayerFoundItems::
	.string "{PLAYER}找到了\n{STR_VAR_1}个{STR_VAR_2}！$"
