Questionnaire_Text_FillOut::
	.string "这里一张问卷调查，\n要填一下吗？$"

Questionnaire_Text_ThankYou::
	.string "谢谢您抽出时间来\n填写我们的调查表，\p您的反馈将成为\n我们的参考。$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "啊，你好！\n你知道这些短语吗？\p那么说你一定知道\n关于神秘礼物的事情了。\p从现在起，你将会\n收到神秘礼物！$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "你保存游戏后，就可以\n接收神秘礼物了。$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "啊，你好！\n你知道这些短语吗？\p那么说你一定知道\n关于神秘事件的事情了。$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "你保存游戏后，就可以\n接收神秘事件了。$"

MysteryGift_Text_TheresATicketForYou::
	.string "感谢使用神秘\n事件系统。\p你是{PLAYER}吧，\n这是给你的船票。$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "这个看起来能在\n水静市的港口使用。\p不如去试试\n能到什么地方？$"
