	.align 2
gText_ConfirmSave::
	.string "要将现在的冒险进度\n"
	.string "写到记录中保存起来吗？$"

gText_AlreadySavedFile::
	.string "将原来保存的记录，\n"
	.string "从头覆盖掉可以吗？$"

gText_SavingDontTurnOff::
	.string "正在写记录，请不要切断电源。$"

gText_PlayerSavedGame::
    .string "{PLAYER}将记录保存好了！$"

gText_DifferentSaveFile::
	.string "注意！！\p"
	.string "在“从记录继续”的选项里\n"
	.string "已经有了一个先前保存的\l"
	.string "冒险进度了！\p"
	.string "这样做，先前的冒险进度，\n"
	.string "以及已经得到的所有宝可梦和道具\l"
	.string "全部都会消失……\p"
	.string "真的要将原来的记录\n"
	.string "从头覆盖掉吗？$"

gText_SaveError::
    .string "无法写入记录！\p"
    .string "请更换卡带的存档用\n"
    .string "记忆电池或电子基板！$"

gText_SavingDontTurnOffPower::
	.string "正在写记录，请不要切断电源。$"
